apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {{ include "parasol-store-build.name" . }}-pr-merged
  labels:
    {{- include "parasol-store-build.labels" . | nindent 4 }}
spec:
  params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
    - name: source-revision
      description: source revision to build from
      type: string
    - name: dockerfile
      type: string
    - name: output-image
      type: string
    - name: output-image-tag
      type: string
    - name: manifest-repo
      type: string
    - name: manifest-branch-dev
      type: string
    - name: manifest-branch-staging
      type: string
    - name: manifest-branch-prod
      type: string
    - name: manifest-file-dev
      type: string
    - name: manifest-file-staging
      type: string
    - name: manifest-file-prod
      type: string
    - name: git-token-secret-name
      type: string
    - name: git-token-secret-key
      type: string
    - name: git-user
      type: string
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.source-repo)
        - name: REVISION
          value: $(params.source-revision)
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines     
      workspaces:
        - name: output
          workspace: source-folder
    - name: build-source
      runAfter:
        - git-clone
      params:
        - name: GOALS
          value:
            - package
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source-folder
        - name: maven_settings
          workspace: maven-settings
    - name: build-and-push-image
      runAfter:
        - build-source
      params:
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: IMAGE
          value: $(params.output-image):$(params.output-image-tag)
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source-folder
    - name: update-manifest-dev
      runAfter:
        - build-and-push-image
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: update-manifest
          - name: namespace
            value: {{ .Release.Namespace }}
      params:
        - name: IMAGE_TAG
          value: $(params.output-image-tag)
        - name: TARGET_BRANCH
          value: $(params.manifest-branch-dev)
        - name: MANIFEST_FILE
          value: $(params.manifest-file-dev)
        - name: MANIFEST_REPO
          value: $(params.manifest-repo)
        - name: GIT_TOKEN_SECRET_NAME
          value: $(params.git-token-secret-name)
        - name: GIT_TOKEN_SECRET_KEY
          value: $(params.git-token-secret-key)
        - name: GIT_PUSH_USER_NAME
          value: $(params.git-user)
      workspaces:
        - name: source
          workspace: ephemeral
    - name: update-manifest-staging
      runAfter:
        - build-and-push-image
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: update-manifest
          - name: namespace
            value: {{ .Release.Namespace }}
      params:
        - name: IMAGE_TAG
          value: $(params.output-image-tag)
        - name: TARGET_BRANCH
          value: $(params.manifest-branch-staging)
        - name: MANIFEST_FILE
          value: $(params.manifest-file-staging)
        - name: MANIFEST_REPO
          value: $(params.manifest-repo)
        - name: GIT_TOKEN_SECRET_NAME
          value: $(params.git-token-secret-name)
        - name: GIT_TOKEN_SECRET_KEY
          value: $(params.git-token-secret-key)
        - name: GIT_PUSH_USER_NAME
          value: $(params.git-user)
      workspaces:
      - name: source
        workspace: ephemeral
    - name: update-manifest-prod
      runAfter:
        - build-and-push-image
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: update-manifest
          - name: namespace
            value: {{ .Release.Namespace }}
      params:
        - name: IMAGE_TAG
          value: $(params.output-image-tag)
        - name: TARGET_BRANCH
          value: $(params.manifest-branch-prod)
        - name: FEATURE_BRANCH
          value: "feature-$(params.output-image-tag)"
        - name: CREATE_FEATURE_BRANCH
          value: "true"
        - name: MANIFEST_FILE
          value: $(params.manifest-file-prod)
        - name: MANIFEST_REPO
          value: $(params.manifest-repo)
        - name: GIT_TOKEN_SECRET_NAME
          value: $(params.git-token-secret-name)
        - name: GIT_TOKEN_SECRET_KEY
          value: $(params.git-token-secret-key)
        - name: GIT_PUSH_USER_NAME
          value: $(params.git-user)
      workspaces:
        - name: source
          workspace: ephemeral
    - name: open-pr-manifest-prod
      runAfter:
        - update-manifest-prod
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: open-pr
          - name: namespace
            value: {{ .Release.Namespace }}
      params:
        - name: GITLAB_REPO_URL
          value: $(params.manifest-repo)
        - name: SOURCE_BRANCH
          value: "feature-$(params.output-image-tag)"
        - name: TARGET_BRANCH
          value: $(params.manifest-branch-prod)
        - name: PR_TITLE
          value: "Update prod image to $(params.output-image-tag)"
        - name: PR_DESCRIPTION
          value: "Update prod image to $(params.output-image):$(params.output-image-tag)"
        - name: PR_REMOVE_SOURCE_BRANCH
          value: "True"
        - name: GIT_TOKEN_SECRET_NAME
          value: $(params.git-token-secret-name)
        - name: GIT_TOKEN_SECRET_KEY
          value: $(params.git-token-secret-key)        
  workspaces:
    - name: source-folder
    - name: maven-settings
    - name: ephemeral