---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "parasol-store-build.name" . }}-pr-merged
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: git-revision-short
    - name: output-image
    - name: dockerfile
    - name: manifest-repo
    - name: manifest-branch-dev
    - name: manifest-branch-staging
    - name: manifest-branch-prod
    - name: manifest-file-dev
    - name: manifest-file-staging
    - name: manifest-file-prod
    - name: git-token-secret-name
    - name: git-token-secret-key
    - name: git-user
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: {{ include "parasol-store-build.name" . }}-$(uid)
        labels:
          {{- include "parasol-store-build.labels" . | nindent 8 }}
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-revision
            value: $(tt.params.git-revision)
          - name: dockerfile
            value: $(tt.params.dockerfile)
          - name: output-image
            value: $(tt.params.output-image)
          - name: output-image-tag
            value: $(tt.params.git-revision-short)
          - name: manifest-repo
            value: $(tt.params.manifest-repo)
          - name: manifest-branch-dev
            value: $(tt.params.manifest-branch-dev)
          - name: manifest-branch-staging
            value: $(tt.params.manifest-branch-staging)
          - name: manifest-branch-prod
            value: $(tt.params.manifest-branch-prod)
          - name: manifest-file-dev
            value: $(tt.params.manifest-file-dev)
          - name: manifest-file-staging
            value: $(tt.params.manifest-file-staging)
          - name: manifest-file-prod
            value: $(tt.params.manifest-file-prod)
          - name: git-token-secret-name
            value: $(tt.params.git-token-secret-name)
          - name: git-token-secret-key
            value: $(tt.params.git-token-secret-key)
          - name: git-user
            value: $(tt.params.git-user)
        pipelineRef:
          name: {{ include "parasol-store-build.name" . }}-pr-merged
        serviceAccountName: pipeline
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: maven-settings
            emptyDir: {}
          - name: ephemeral
            emptyDir: {}