---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "parasol-store-build.name" . }}-pr-prod-open-secure
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: git-token-secret-name
    - name: git-token-secret-key    
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        #generateName: {{ include "parasol-store-build.name" . }}-prod-check-
        generateName: {{ include "parasol-store-build.name" . }}-prod-check-secure-
        labels:
          {{- include "parasol-store-build.labels" . | nindent 10 }}
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-revision
            value: $(tt.params.git-revision)
          - name: git-token-secret-name
            value: $(tt.params.git-token-secret-name)
          - name: git-token-secret-key
            value: $(tt.params.git-token-secret-key)
        pipelineRef:
          # name: {{ include "parasol-store-build.name" . }}-pr-prod-open
          name: {{ include "parasol-store-build.name" . }}-pr-prod-open-secure
        serviceAccountName: pipeline
